In [1]:
import requests
import pandas as pd
import numpy as np
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
r = requests.get(url)
json = r.json()
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [2]:
%run soup.ipynb #loading dataframes from fbref.com

pl_adv_gk loaded!
pl_std loaded!
pl_shot loaded!
pl_pos loaded!
pl_time loaded!
pl_pass loaded!
pl_pass_type loaded!
pl_msc loaded!
pl_gk loaded!
pl_goal loaded!

In [3]:
elements_df = pd.DataFrame(json['elements'])
teams_df = pd.DataFrame(json['teams'])

In [4]:
def del_id_pl(df):#removing identical players from dataframes
    df.sort_values('player',inplace=True)
    df.reset_index(inplace=True,drop=True)
    for row in df.index:
        if row>0:
            try:
                if df['player'][row]==df['player'][row-1]:
                    if df['minutes_90s'][row]>df['minutes_90s'][row-1]:#checking minutes per 90
                        df.drop(index=row-1,inplace=True)
                    else:
                        df.drop(index=row,inplace=True)                    
            except:
                try:
                    if df['minutes'][row]>df['minutes'][row-1]: #checking minutes
                        df.drop(index=row-1,inplace=True)
                    else:
                        df.drop(index=row,inplace=True)
                except:
                    continue
    df.reset_index(inplace=True,drop=True)
for df in df_fbref_list:
    del_id_pl(df)

In [5]:
pl_pass.loc[pl_pass['player']=='Theo Walcott']

,player,position,squad,minutes_90s,assisted_shots,passes_into_penalty_area,crosses_into_penalty_area
394,Theo Walcott,"FW,MF",Southampton,5.7,5,2,0

In [6]:
def del_null_fbref(df):#remove players who haven't played (fbref)
    for row in df.index:
        if df['games'][row]==0:
            df.drop(index=row,inplace=True)
    df.reset_index(inplace=True,drop=True)
del_null_fbref(pl_time)

In [7]:
pl_time.loc[pl_time['player']=='Diogo Jota']

,player,position,squad,games,minutes,minutes_per_game,minutes_pct,minutes_90s,games_starts,games_complete,...,minutes_per_sub,unused_subs,points_per_match,on_goals_for,on_goals_against,on_xg_for,on_xg_against,xg_plus_minus,xg_plus_minus_per90,xg_plus_minus_wowy
107,Diogo Jota,FW,Liverpool,9,503,56,50.8,5.6,5,3,...,16,0,2,12,11,11.5,10.2,1.3,0.23,-1.11

In [8]:
pd.options.mode.chained_assignment = None
def correct_team_names(teams_df):
    for row in teams_df.index: #changing team names in fantasy stats to use in fbref
        team_name=teams_df['name'][row]
        if team_name=='Leicester':
            teams_df['name'][row]='Leicester City'
        if team_name=='Man City':
            teams_df['name'][row]='Manchester City'
        if team_name=='Man Utd':
            teams_df['name'][row]='Manchester Utd'
        if team_name=='Newcastle':
            teams_df['name'][row]='Newcastle Utd'
        if team_name=='Spurs':
            teams_df['name'][row]='Tottenham'
        if team_name=='Leeds':
            teams_df['name'][row]='Leeds United'
correct_team_names(teams_df)
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1190,1210,1170,1210,1190,1200,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1150,1160,1150,1150,1180,1210,2
2,36,0,None,3,0,Brighton,0,0,0,BHA,...,None,False,0,1080,1100,1150,1180,1090,1100,131
3,90,0,None,4,0,Burnley,0,0,0,BUR,...,None,False,0,1050,1080,1120,1190,1010,1030,43
4,8,0,None,5,0,Chelsea,0,0,0,CHE,...,None,False,0,1260,1280,1240,1280,1270,1310,4
5,31,0,None,6,0,Crystal Palace,0,0,0,CRY,...,None,False,0,1110,1150,1100,1150,1020,1050,6
6,11,0,None,7,0,Everton,0,0,0,EVE,...,None,False,0,1180,1210,1150,1170,1210,1250,7
7,54,0,None,8,0,Fulham,0,0,0,FUL,...,None,False,0,1000,1020,1020,1030,1020,1020,34
8,13,0,None,9,0,Leicester City,0,0,0,LEI,...,None,False,0,1220,1240,1190,1190,1200,1180,26
9,2,0,None,10,0,Leeds United,0,0,0,LEE,...,None,False,0,1100,1130,1060,1110,1130,1160,9
10,14,0,None,11,0,Liverpool,0,0,0,LIV,...,None,False,0,1320,1360,1240,1320,1330,1350,10
11,43,0,None,12,0,Manchester City,0,0,0,MCI,...,None,False,0,1310,1360,1260,1320,1330,1350,11
12,1,0,None,13,0,Manchester Utd,0,0,0,MUN,...,None,False,0,1230,1230,1220,1230,1250,1260,12
13,4,0,None,14,0,Newcastle Utd,0,0,0,NEW,...,None,False,0,1100,1130,1100,1120,1010,1060,23
14,49,0,None,15,0,Sheffield Utd,0,0,0,SHU,...,None,False,0,1070,1100,1110,1130,1010,1050,18
15,20,0,None,16,0,Southampton,0,0,0,SOU,...,None,False,0,1150,1180,1140,1200,1110,1160,20
16,6,0,None,17,0,Tottenham,0,0,0,TOT,...,None,False,0,1270,1280,1190,1240,1280,1320,21
17,35,0,None,18,0,West Brom,0,0,0,WBA,...,None,False,0,1010,1030,1020,1020,1000,1010,36
18,21,0,None,19,0,West Ham,0,0,0,WHU,...,None,False,0,1140,1170,1150,1160,1170,1180,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,...,None,False,0,1160,1190,1180,1220,1100,1170,38

In [9]:
teams_list=[]
for team in teams_df['name']:
    teams_list.append(team)
teams_list

['Arsenal',
 'Aston Villa',
 'Brighton',
 'Burnley',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Leicester City',
 'Leeds United',
 'Liverpool',
 'Manchester City',
 'Manchester Utd',
 'Newcastle Utd',
 'Sheffield Utd',
 'Southampton',
 'Tottenham',
 'West Brom',
 'West Ham',
 'Wolves']

In [10]:
def add_team_name(df):#adding team name
    df['team_name']='' 
    for row in df.index: 
        team_id=df['team'][row]
        team_row=teams_df.loc[teams_df['id']==team_id]
        team_row.index=[0]
        team_name=team_row['name'][0]
        df['team_name'][row]=team_name

In [11]:
def remove_null_players(df):# remove players who haven't played yet (fantasy)
    for row in df.index: 
        if df['minutes'][row]==0.:
            df.drop(index=row,inplace=True)
    df.reset_index(inplace=True,drop=True)
    return df
global players
players=remove_null_players(elements_df)
add_team_name(players)

In [12]:
def update_position(df):#Updating position slot
    for row in df.index: 
        pos=df['element_type'][row]
        if pos==1:
            df['element_type'][row]='GK'
        if pos==2:
            df['element_type'][row]='DF'
        if pos==3:
            df['element_type'][row]='MF'
        if pos==4:
            df['element_type'][row]='FW'
update_position(players)
players[['web_name','element_type']]

       web_name element_type
0    David Luiz           DF
1    Aubameyang           MF
2     Lacazette           FW
3       Mustafi           DF
4          Leno           GK
..          ...          ...
428      Marçal           DF
429     Vitinha           MF
430      Hoever           DF
431      Semedo           DF
432   Ait Nouri           DF

[433 rows x 2 columns]

In [13]:
def add_full_name(df):#add full name to players
    df['name']=''
    for row in df.index:
        first_name=df['first_name'][row]
        web_name=df['web_name'][row]
        if first_name in web_name: #build a name for checking
            name=web_name
        else:
            name=first_name+" "+web_name
        df['name'][row]=name
add_full_name(players)

In [14]:
def correct_bad_names(df):
    df.loc[df['player']=='Jóhann Berg Guðmundsson','player']='Johann Berg Gudmundsson'
    df.loc[df['player']=='İlkay Gündoğan','player']='Ilkay Gündogan'
    df.loc[df['player']=='Carlos Vinícius','player']='Carlos Vinicius'
    df.loc[df['player']=='Łukasz Fabiański','player']='Lukasz Fabianski'
    df.loc[df['player']=='Tomáš Souček','player']='Tomas Soucek'
    df.loc[df['player']=='Dan Nlundulu','player']="Daniel N'Lundulu"

In [15]:
pl_df_list=[pl_goal,pl_msc,pl_pass_type,pl_pass,pl_time,pl_pos,pl_shot,pl_std]
def find_names(df,players):
    df['id']=0
    correct_bad_names(df)
    df_groups=df.groupby('squad')
    pl_groups=players.groupby('team_name')    
    for team in teams_list:
        fbref=df_groups.get_group(team)
        fantasy=pl_groups.get_group(team)
        for row in fantasy.index:
            checked=False
            player_id=fantasy['id'][row]
            team_name=fantasy['team_name'][row]
            name=fantasy['name'][row]
            first_name=fantasy['first_name'][row]
            second_name=fantasy['second_name'][row]
            web_name=fantasy['web_name'][row]
            pos=fantasy['element_type'][row]
            for s_row in fbref.index:
                fb_name=fbref['player'][s_row]              
                fb_team=fbref['squad'][s_row]
                fb_pos=fbref['position'][s_row]
                if name==fb_name or first_name+' '+second_name==fb_name: #find names which are totally equal
                    checked=True
                    df.loc[df['player']==fb_name,'id']=player_id
                    fantasy.drop(index=row,inplace=True)
                    fbref.drop(index=s_row,inplace=True)
                    break
            if checked==False: #find names which are not totally equal
                for s_row in fbref.index:
                    fb_name=fbref['player'][s_row]              
                    fb_team=fbref['squad'][s_row]
                    fb_pos=fbref['position'][s_row]
                    if web_name in fb_name or second_name in fb_name:
                        df.loc[df['player']==fb_name,'id']=player_id
                        checked=True
                    elif (first_name in fb_name or fb_name in first_name) and pos in fb_pos:
                        df.loc[df['player']==fb_name,'id']=player_id
                        checked=True
for df in pl_df_list:#finding names
    find_names(df,players)

In [16]:
pl_std.loc[pl_std['squad']=='Manchester City']

,player,position,squad,games,games_starts,minutes,goals,assists,pens_made,pens_att,...,goals_assists_pens_per90,xg,npxg,xa,xg_per90,xa_per90,xg_xa_per90,npxg_per90,npxg_xa_per90,id
42,Aymeric Laporte,DF,Manchester City,4,4,360,0,0,0,0,...,0.00,0.2,0.2,0.2,0.04,0.06,0.10,0.04,0.10,280
52,Benjamin Mendy,DF,Manchester City,5,5,430,1,0,0,0,...,0.21,0.1,0.1,0.0,0.02,0.01,0.02,0.02,0.02,274
55,Bernardo Silva,"MF,FW",Manchester City,6,4,374,0,0,0,0,...,0.00,0.3,0.3,0.1,0.07,0.03,0.09,0.07,0.09,281
115,Ederson,GK,Manchester City,10,10,900,0,0,0,0,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,278
124,Eric García,DF,Manchester City,3,2,201,0,0,0,0,...,0.00,0.0,0.0,0.1,0.01,0.04,0.04,0.01,0.04,288
135,Fernandinho,MF,Manchester City,5,2,201,0,0,0,0,...,0.00,0.5,0.5,0.0,0.20,0.00,0.20,0.20,0.20,266
137,Ferrán Torres,FW,Manchester City,7,5,397,1,1,0,0,...,0.45,1.9,1.9,0.2,0.43,0.04,0.47,0.43,0.47,287
143,Gabriel Jesus,FW,Manchester City,5,5,450,2,1,0,0,...,0.60,1.6,1.6,1.1,0.31,0.22,0.53,0.31,0.53,282
211,John Stones,DF,Manchester City,3,3,270,0,0,0,0,...,0.00,0.1,0.1,0.1,0.02,0.02,0.04,0.02,0.04,273
222,João Cancelo,"DF,MF",Manchester City,6,6,540,0,1,0,0,...,0.17,0.1,0.1,1.3,0.02,0.22,0.24,0.02,0.24,277
238,Kevin De Bruyne,MF,Manchester City,9,8,743,2,6,2,3,...,0.73,4.7,2.4,3.3,0.57,0.40,0.96,0.29,0.69,272
246,Kyle Walker,DF,Manchester City,9,9,797,1,1,0,0,...,0.23,0.2,0.2,0.3,0.02,0.03,0.05,0.02,0.05,270
253,Liam Delap,FW,Manchester City,1,0,40,0,0,0,0,...,0.00,0.0,0.0,0.0,0.06,0.00,0.06,0.06,0.06,539
302,Nathan Aké,DF,Manchester City,4,3,290,1,0,0,0,...,0.31,0.1,0.1,0.0,0.02,0.01,0.03,0.02,0.03,279
317,Oleksandr Zinchenko,DF,Manchester City,1,0,13,0,0,0,0,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,283
334,Phil Foden,"FW,DF",Manchester City,8,4,429,2,1,0,0,...,0.63,1.5,1.5,0.3,0.30,0.06,0.36,0.30,0.36,284
337,Raheem Sterling,FW,Manchester City,9,8,729,3,1,0,0,...,0.49,2.9,2.9,1.0,0.35,0.13,0.48,0.35,0.48,276
346,Riyad Mahrez,"FW,DF",Manchester City,8,8,681,4,1,0,0,...,0.66,1.8,1.8,2.8,0.24,0.37,0.60,0.24,0.60,275
354,Rodri,MF,Manchester City,10,10,855,0,0,0,0,...,0.00,0.3,0.3,0.3,0.04,0.03,0.07,0.04,0.07,286
364,Rúben Dias,DF,Manchester City,8,8,699,0,0,0,0,...,0.00,0.8,0.8,0.0,0.10,0.00,0.11,0.10,0.11,556
378,Sergio Agüero,FW,Manchester City,2,2,109,0,0,0,0,...,0.00,0.2,0.2,0.6,0.14,0.46,0.60,0.14,0.60,268
431,Ilkay Gündogan,MF,Manchester City,6,4,392,0,0,0,0,...,0.00,0.2,0.2,0.5,0.04,0.11,0.15,0.04,0.15,271

In [17]:
posts = players.groupby('element_type')

In [18]:
GK = posts.get_group('GK')
DF = posts.get_group('DF')
MF = posts.get_group('MF')
FW = posts.get_group('FW')

In [19]:
#find names for gk
gk_df_list=[pl_gk,pl_adv_gk] 
for df in gk_df_list:
    find_names(df,GK)
pl_adv_gk

,player,position,squad,minutes_90s,psxg_gk,psnpxg_per_shot_on_target_against,psxg_net_gk,psxg_net_per90_gk,id
0,Adrián,GK,Liverpool,2.0,7.1,0.45,-1.9,-0.93,245
1,Alisson,GK,Liverpool,8.0,8.7,0.35,0.7,0.09,252
2,Alphonse Areola,GK,Fulham,10.0,19.4,0.31,1.4,0.14,516
3,Kepa Arrizabalaga,GK,Chelsea,3.0,4.8,0.34,-1.2,-0.42,112
4,Willy Caballero,GK,Chelsea,1.0,1.5,0.49,-1.5,-1.54,101
5,Karl Darlow,GK,Newcastle Utd,10.0,14.6,0.24,0.6,0.06,325
6,Ederson,GK,Manchester City,10.0,9.8,0.27,-1.2,-0.12,278
7,Lukasz Fabianski,GK,West Ham,11.0,15.9,0.35,1.9,0.17,431
8,David de Gea,GK,Manchester Utd,8.5,14.0,0.40,-1.0,-0.12,291
9,Vicente Guaita,GK,Crystal Palace,11.0,16.1,0.29,0.1,0.01,128
10,Dean Henderson,GK,Manchester Utd,1.5,1.7,0.22,0.7,0.50,305
11,Sam Johnstone,GK,West Brom,11.0,24.8,0.35,3.8,0.35,417
12,Caoimhin Kelleher,GK,Liverpool,1.0,0.9,0.30,0.9,0.91,560
13,Bernd Leno,GK,Arsenal,11.0,12.9,0.31,-0.1,-0.01,8
14,Hugo Lloris,GK,Tottenham,11.0,7.5,0.16,-0.5,-0.05,383
15,Emiliano Martínez,GK,Aston Villa,9.0,13.6,0.37,0.6,0.07,12
16,Alex McCarthy,GK,Southampton,11.0,16.4,0.30,-0.6,-0.06,363
17,Edouard Mendy,GK,Chelsea,7.0,2.5,0.21,0.5,0.07,548
18,Illan Meslier,GK,Leeds United,11.0,21.2,0.34,2.2,0.20,213
19,Robin Olsen,GK,Everton,1.0,2.4,0.53,0.4,0.43,573
20,Rui Patrício,GK,Wolves,11.0,11.5,0.27,-1.5,-0.14,455
21,Bailey Peacock-Farrell,GK,Burnley,1.0,4.4,0.62,-0.6,-0.65,99
22,Jordan Pickford,GK,Everton,10.0,12.8,0.27,-3.2,-0.32,157
23,Nick Pope,GK,Burnley,9.0,13.9,0.31,1.9,0.22,96
24,Aaron Ramsdale,GK,Sheffield Utd,11.0,19.2,0.32,1.2,0.11,483
25,Marek Rodák,GK,Fulham,1.0,2.5,0.61,-0.5,-0.55,186
26,Mathew Ryan,GK,Brighton,10.0,11.9,0.34,-3.1,-0.31,70
27,Robert Sánchez,GK,Brighton,1.0,1.6,0.37,-0.4,-0.38,597
28,Kasper Schmeichel,GK,Leicester City,11.0,15.2,0.29,1.2,0.11,217

In [20]:
pd.options.mode.chained_assignment = None 
def add_cl(post,df,cl): #add columns from teams_df to players
    post[cl] = 0 
    for row in post.index:
        team_id = post['team'][row] 
        team_row = df.loc[df['id'] == team_id]  
        post[cl][row] = team_row[cl]

In [21]:
stg_list=['strength_attack_home','strength_attack_away','strength_defence_home','strength_defence_away']
for stg in stg_list: #adding strength defence & attack to DF & MF
    add_cl(DF,teams_df,stg)
    add_cl(MF,teams_df,stg)
add_cl(FW,teams_df,stg_list[0])#add to GK
add_cl(FW,teams_df,stg_list[1])
add_cl(GK,teams_df,stg_list[2])#add to FW
add_cl(GK,teams_df,stg_list[3])

In [23]:
def add_cl_fbref(post,fbref,cl_list): #add columns from fbref to fantasy
    for cl in cl_list:
        post[cl]=0.0
    for row in post.index:
        for cl in cl_list:
            player_id=post['id'][row]
            fb_row=fbref.loc[fbref['id']==player_id]
            fb_row.index=[0]
            post[cl][row]=fb_row[cl][0]

In [24]:
fbref_cl=[[pl_std,std_cl],[pl_shot,shot_cl],[pl_pass,pass_cl],[pl_pass_type,pass_type_cl] 
    ,[pl_pos,pos_cl], [pl_goal,goal_cl], [pl_msc,msc_cl] ,  [pl_time,time_cl]] #fbref dataframes with desired columns

fbref_gk_cl=[[pl_gk,gk_cl],[pl_adv_gk,adv_gk_cl]]
post_list=[DF,MF,FW]
for post in post_list: #updating posts with fbref data
    for cl in fbref_cl:
        add_cl_fbref(post,cl[0],cl[1])
for cl in fbref_gk_cl:
    add_cl_fbref(GK,cl[0],cl[1])

In [25]:
%run columns.ipynb

In [ ]:
#MF.to_excel('C:\\Users\\farha\\MF.xlsx')
#FW.to_excel('C:\\Users\\farha\\FW.xlsx')
#DF.to_excel('C:\\Users\\farha\\DF.xlsx')
#GK.to_excel('C:\\Users\\farha\\GK.xlsx')

In [26]:
FW

,id,web_name,first_name,second_name,team,now_cost,cost_change_start,total_points,selected_by_percent,minutes,...,creativity_rank_type,threat_rank,threat_rank_type,transfers_in,transfers_out,ep_next,status,own_goals,team_code,name
0,6,Lacazette,Alexandre,Lacazette,1,83,-2,29,2.7,584,...,19,38,19,276846,421501,1.7,a,0,3,Alexandre Lacazette
1,22,Nketiah,Edward,Nketiah,1,55,-5,16,0.6,160,...,39,154,41,34992,128076,1.3,a,0,3,Edward Nketiah
2,50,Davis,Keinan,Davis,2,43,-2,1,7.4,28,...,46,325,50,524522,1055929,0.0,d,0,7,Keinan Davis
3,514,Watkins,Ollie,Watkins,2,61,1,49,8.1,810,...,4,15,8,1036125,551759,1.0,a,0,7,Ollie Watkins
4,68,Maupay,Neal,Maupay,3,62,-3,40,2.3,759,...,11,11,7,609914,619805,0.2,a,0,36,Neal Maupay
5,78,Connolly,Aaron,Connolly,3,53,-2,22,0.5,413,...,28,78,33,69409,82533,0.8,a,0,36,Aaron Connolly
6,588,Welbeck,Danny,Welbeck,3,55,0,22,0.9,362,...,25,62,26,74779,14471,5.8,a,0,36,Danny Welbeck
7,86,Rodriguez,Jay,Rodriguez,4,58,-2,13,0.3,407,...,36,138,40,10807,48958,1.7,a,0,90,Jay Rodriguez
8,87,Barnes,Ashley,Barnes,4,60,0,12,0.1,476,...,14,68,28,9045,13510,0.0,a,0,90,Ashley Barnes
9,91,Wood,Chris,Wood,4,62,-3,30,1.0,869,...,26,28,15,93676,186226,3.0,a,0,90,Chris Wood
10,93,Vydra,Matej,Vydra,4,49,-1,7,0.6,139,...,41,155,42,70301,84842,-0.7,a,0,90,Matej Vydra
11,103,Giroud,Olivier,Giroud,5,67,-3,11,1.2,125,...,34,124,38,60158,77705,3.2,a,0,8,Olivier Giroud
12,117,Werner,Timo,Werner,5,95,0,55,22.4,933,...,3,6,4,1302569,2869181,4.5,a,0,8,Timo Werner
13,118,Abraham,Tammy,Abraham,5,72,-3,39,3.0,556,...,12,27,14,184353,290849,4.5,a,0,8,Tammy Abraham
14,108,Batshuayi,Michy,Batshuayi,6,58,-2,18,0.7,386,...,31,75,31,52717,156583,0.8,a,0,31,Michy Batshuayi
15,132,Benteke,Christian,Benteke,6,55,0,19,0.3,148,...,29,55,24,26645,28193,4.5,a,0,31,Christian Benteke
16,140,Ayew,Jordan,Ayew,6,57,-3,25,1.8,600,...,37,77,32,116380,434743,1.2,a,0,31,Jordan Ayew
17,153,Tosun,Cenk,Tosun,7,60,0,2,0.0,32,...,49,355,54,1223,1233,-0.2,a,0,11,Cenk Tosun
18,164,Calvert-Lewin,Dominic,Calvert-Lewin,7,80,10,78,61.4,968,...,9,1,1,4490284,878608,6.5,a,0,11,Dominic Calvert-Lewin
19,166,Richarlison,Richarlison,de Andrade,7,78,-2,36,4.5,637,...,8,20,9,493408,896880,4.2,a,0,11,Richarlison
20,169,Kean,Moise,Kean,7,58,-2,2,0.2,13,...,53,304,49,7904,34863,0.0,n,0,11,Moise Kean
21,181,Decordova-Reid,Bobby,Decordova-Reid,8,53,-2,30,0.3,603,...,27,49,22,31896,23227,2.2,a,0,54,Bobby Decordova-Reid
22,184,Mitrović,Aleksandar,Mitrović,8,56,-4,30,5.0,692,...,6,21,10,489225,1700698,-0.8,a,0,54,Aleksandar Mitrović
23,224,Vardy,Jamie,Vardy,9,103,3,74,29.7,828,...,21,9,5,2259305,1600273,5.5,a,0,13,Jamie Vardy
24,233,Iheanacho,Kelechi,Iheanacho,9,56,-4,6,0.3,142,...,35,100,35,12309,43120,1.2,a,0,13,Kelechi Iheanacho
25,579,Slimani,Islam,Slimani,9,50,0,1,0.1,19,...,47,330,51,7587,5455,0.5,a,0,13,Islam Slimani
26,202,Bamford,Patrick,Bamford,10,62,7,70,37.1,940,...,22,3,2,3349006,1221906,4.0,a,0,2,Patrick Bamford
27,492,Rodrigo,Rodrigo,Moreno,10,57,-3,21,2.1,362,...,10,45,20,133220,543947,1.0,a,0,2,Rodrigo
28,249,Firmino,Roberto,Firmino,11,92,-3,37,2.3,870,...,5,10,6,108514,275969,4.8,a,0,14,Roberto Firmino
29,256,Origi,Divock,Origi,11,52,-3,1,0.6,1,...,57,573,71,19407,72945,1.8,a,0,14,Divock Origi
30,268,Agüero,Sergio,Agüero,12,103,-2,3,1.2,109,...,38,279,47,214133,415361,0.5,a,0,43,Sergio Agüero
31,282,Jesus,Gabriel Fernando,de Jesus,12,94,-1,24,2.4,450,...,20,63,27,305917,273039,3.5,a,0,43,Gabriel Fernando Jesus
32,539,Delap,Liam,Delap,12,44,-1,1,1.0,39,...,54,340,53,159336,111381,0.5,a,0,43,Liam Delap
33,293,Ighalo,Odion,Ighalo,13,62,-3,1,0.2,9,...,58,357,55,6466,20897,-0.5,a,0,1,Odion Ighalo
34,303,Martial,Anthony,Martial,13,87,-3,11,3.4,438,...,40,54,23,555545,1150106,0.6,d,0,1,Anthony Martial
35,569,Cavani,Edinson,Cavani,13,81,1,23,2.6,172,...,44,72,29,326602,149911,3.6,d,0,1,Edinson Cavani
36,320,Carroll,Andy,Carroll,14,52,-3,11,0.3,178,...,45,123,37,44793,66182,0.2,d,0,4,Andy Carroll
37,340,Joelinton,Joelinton Cássio,Apolinário de Lira,14,57,-3,21,0.4,487,...,23,89,34,20912,28994,7.0,a,0,4,Joelinton Cássio Joelinton
38,506,Wilson,Callum,Wilson,14,66,1,67,15.0,787,...,13,24,12,1803839,1450019,6.5,a,0,4,Callum Wilson
39,262,Brewster,Rhian,Brewster,15,45,0,9,6.4,301,...,30,207,44,683305,620276,1.0,a,0,49,Rhian Brewster
40,343,Sharp,Billy,Sharp,15,56,-4,11,0.1,129,...,51,170,43,8445,22719,0.0,a,0,49,Billy Sharp
41,344,McGoldrick,David,McGoldrick,15,53,-2,24,0.6,478,...,33,133,39,63322,95777,0.7,a,0,49,David McGoldrick
42,357,McBurnie,Oliver,McBurnie,15,56,-4,26,0.3,729,...,7,22,11,14362,47035,4.0,a,0,49,Oliver McBurnie
43,359,Mousset,Lys,Mousset,15,58,-2,1,0.1,16,...,43,294,48,2096,27996,0.1,d,0,49,Lys Mousset
44,361,Long,Shane,Long,16,52,-3,8,0.6,61,...,52,331,52,34277,97147,0.7,a,0,20,Shane Long
45,366,Ings,Danny,Ings,16,83,-2,55,6.4,669,...,17,33,18,787604,1998117,2.7,a,0,20,Danny Ings
46,377,Adams,Che,Adams,16,60,0,52,7.3,945,...,2,29,16,651474,424218,3.7,a,0,20,Che Adams
47,381,Obafemi,Michael,Obafemi,16,47,-3,1,1.0,13,...,56,522,62,52389,164623,0.0,a,0,20,Michael Obafemi
48,590,N'Lundulu,Daniel,N'Lundulu,16,45,0,2,0.1,2,...,55,487,58,10012,5233,0.3,a,0,20,Daniel N'Lundulu
49,388,Kane,Harry,Kane,17,109,4,98,40.3,983,...,1,4,3,2932095,1274792,6.5,a,0,6,Harry Kane
50,564,Carlos Vinicius,Carlos Vinicius,Alves Morais,17,69,-1,1,0.0,12,...,50,271,46,4601,4101,0.5,a,0,6,Carlos Vinicius
51,358,Callum Robinson,Callum,Robinson,18,55,0,29,0.6,537,...,18,74,30,129236,117019,0.8,a,0,35,Callum Robinson
52,408,Robson-Kanu,Hal,Robson-Kanu,18,52,-3,5,0.1,137,...,48,253,45,7798,29898,0.0,i,0,35,Hal Robson-Kanu
53,582,Grant,Karlan,Grant,18,59,-1,21,0.1,524,...,32,56,25,8628,5841,1.5,a,0,35,Karlan Grant
54,437,Antonio,Michail,Antonio,19,62,-3,28,1.9,526,...,24,25,13,146788,718371,0.0,d,0,21,Michail Antonio
55,441,Haller,Sébastien,Haller,19,61,-4,25,0.4,438,...,16,47,21,28110,47754,4.0,a,0,21,Sébastien Haller
56,460,Jiménez,Raúl,Jiménez,20,82,-3,43,7.0,824,...,15,32,17,1156983,2045096,0.0,i,1,39,Raúl Jiménez
57,504,Fabio Silva,Fabio,Silva,20,52,-3,6,0.6,143,...,42,105,36,37460,93276,0.7,a,0,39,Fabio Silva