In [1]:
import requests
import pandas as pd
import numpy as np
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
r = requests.get(url)
json = r.json()
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [2]:
elements_df = pd.DataFrame(json['elements'])
teams_df = pd.DataFrame(json['teams'])

In [123]:
standard=pd.read_excel("C://Users//farha//Downloads//sportsref_download (1).xlsx",header=1)

In [126]:
standard=standard.sort_values('Player')# remove players from 2 team
standard.index=list(range(len(standard.index)))
for row in standard.index:
    if row>0:
        try:
            if standard['Player'][row]==standard['Player'][row-1]:
                standard=standard.drop(index=row)
        except:
            continue        
standard.index=list(range(len(standard.index)))
standard.loc[standard['Player']=='Ross Barkley']

,Rk,Player,Nation,Pos,Squad,Age,Born▼,MP,Starts,Min,...,G+A-PK,xG,npxG,xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA,Matches
350,242,Ross Barkley,eng ENG,MF,Aston Villa,26-354,1993.0,6,6,454,...,0.59,1.5,1.5,1.7,0.3,0.34,0.64,0.3,0.64,Matches

In [127]:
for row in teams_df.index: #changing team names in fantasy stats to use in fbref
    team_name=teams_df['name'][row]
    if team_name=='Leicester':
        teams_df['name'][row]='Leicester City'
    if team_name=='Man City':
        teams_df['name'][row]='Manchester City'
    if team_name=='Man Utd':
        teams_df['name'][row]='Manchester Utd'
    if team_name=='Newcastle':
        teams_df['name'][row]='Newcastle Utd'
    if team_name=='Spurs':
        teams_df['name'][row]='Tottenham'
    if team_name=='Leeds':
        teams_df['name'][row]='Leeds United'
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1190,1210,1170,1210,1190,1200,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1150,1160,1150,1150,1180,1210,2
2,36,0,None,3,0,Brighton,0,0,0,BHA,...,None,False,0,1080,1100,1150,1180,1090,1100,131
3,90,0,None,4,0,Burnley,0,0,0,BUR,...,None,False,0,1050,1080,1120,1190,1010,1030,43
4,8,0,None,5,0,Chelsea,0,0,0,CHE,...,None,False,0,1260,1280,1240,1280,1270,1310,4
5,31,0,None,6,0,Crystal Palace,0,0,0,CRY,...,None,False,0,1110,1150,1100,1150,1020,1050,6
6,11,0,None,7,0,Everton,0,0,0,EVE,...,None,False,0,1180,1210,1150,1170,1210,1250,7
7,54,0,None,8,0,Fulham,0,0,0,FUL,...,None,False,0,1000,1020,1020,1030,1020,1020,34
8,13,0,None,9,0,Leicester City,0,0,0,LEI,...,None,False,0,1220,1240,1190,1190,1200,1180,26
9,2,0,None,10,0,Leeds United,0,0,0,LEE,...,None,False,0,1100,1130,1060,1110,1130,1160,9
10,14,0,None,11,0,Liverpool,0,0,0,LIV,...,None,False,0,1320,1360,1240,1320,1330,1350,10
11,43,0,None,12,0,Manchester City,0,0,0,MCI,...,None,False,0,1310,1360,1260,1320,1330,1350,11
12,1,0,None,13,0,Manchester Utd,0,0,0,MUN,...,None,False,0,1230,1230,1220,1230,1250,1260,12
13,4,0,None,14,0,Newcastle Utd,0,0,0,NEW,...,None,False,0,1100,1130,1100,1120,1010,1060,23
14,49,0,None,15,0,Sheffield Utd,0,0,0,SHU,...,None,False,0,1070,1100,1110,1130,1010,1050,18
15,20,0,None,16,0,Southampton,0,0,0,SOU,...,None,False,0,1150,1180,1140,1200,1110,1160,20
16,6,0,None,17,0,Tottenham,0,0,0,TOT,...,None,False,0,1270,1280,1190,1240,1280,1320,21
17,35,0,None,18,0,West Brom,0,0,0,WBA,...,None,False,0,1010,1030,1020,1020,1000,1010,36
18,21,0,None,19,0,West Ham,0,0,0,WHU,...,None,False,0,1140,1170,1150,1160,1170,1180,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,...,None,False,0,1160,1190,1180,1220,1100,1170,38

In [128]:
elements_df['team_name']='' #adding team name to elements_df
for row in elements_df.index: 
    team_id=elements_df['team'][row]
    team_row=teams_df.loc[teams_df['id']==team_id]
    team_row.index=[0]
    team_name=team_row['name'][0]
    elements_df['team_name'][row]=team_name

In [129]:
players=elements_df
for row in elements_df.index: # remove players who haven't played yet.
    if elements_df['minutes'][row]==0.:
        players=players.drop(index=row)
players.index=list(range(len(players.index)))
players

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name
0,100.0,100.0,41270,0,0,0,0,0,2,0.7,...,73,284,94,NaN,,4.0,,NaN,,Arsenal
1,100.0,100.0,54694,0,0,-3,3,0,3,4.3,...,20,39,22,NaN,,NaN,,1.0,,Arsenal
2,NaN,NaN,59966,-1,1,-2,2,0,4,1.7,...,18,61,17,NaN,,NaN,,3.0,,Arsenal
3,100.0,100.0,69140,0,0,0,0,0,2,1.0,...,211,395,149,NaN,,NaN,,NaN,,Arsenal
4,NaN,NaN,80201,0,0,0,0,2,1,5.7,...,59,160,7,NaN,,NaN,,NaN,,Arsenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,100.0,100.0,111291,0,0,-2,2,0,2,0.0,...,95,336,119,NaN,,NaN,,NaN,,Wolves
421,NaN,NaN,437858,0,0,-2,2,0,3,-0.3,...,214,375,167,NaN,,NaN,,NaN,,Wolves
422,NaN,NaN,441271,0,0,0,0,0,2,-0.5,...,127,361,130,NaN,,NaN,,NaN,,Wolves
423,NaN,NaN,200402,0,0,1,-1,0,2,3.0,...,54,147,44,NaN,,NaN,,NaN,,Wolves
424,75.0,75.0,448514,0,0,0,0,1,2,3.2,...,59,293,101,NaN,,NaN,,NaN,,Wolves

In [130]:
for row in players.index: #Updating position slot
    pos=players['element_type'][row]
    if pos==1:
        players['element_type'][row]='GK'
    if pos==2:
        players['element_type'][row]='DF'
    if pos==3:
        players['element_type'][row]='MF'
    if pos==4:
        players['element_type'][row]='FW'
players[['web_name','element_type']]

       web_name element_type
0    David Luiz           DF
1    Aubameyang           MF
2     Lacazette           FW
3       Mustafi           DF
4          Leno           GK
..          ...          ...
420      Marçal           DF
421     Vitinha           MF
422      Hoever           DF
423      Semedo           DF
424   Ait Nouri           DF

[425 rows x 2 columns]

In [131]:
#correct bad names
standard.loc[standard['Player']=='Jóhann Berg Guðmundsson','Player']='Johann Berg Gudmundsson'
standard.loc[standard['Player']=='İlkay Gündoğan','Player']='Ilkay Gündogan'
standard.loc[standard['Player']=='Carlos','Player']='Carlos Vinicius'
standard.loc[standard['Player']=='Łukasz Fabiański','Player']='Lukasz Fabianski'
standard.loc[standard['Player']=='Tomáš Souček','Player']='Tomas Soucek'
standard.loc[standard['Player']=='Dan Nlundulu','Player']="Daniel N'Lundulu"
players['name']=''
for row in players.index:
    checked=False 
    team_name=players['team_name'][row]
    first_name=players['first_name'][row]
    second_name=players['second_name'][row]
    web_name=players['web_name'][row]
    pos=players['element_type'][row]
    if first_name in web_name: #build a name for checking
        name=web_name
    else:
        name=first_name+" "+web_name
    players['name'][row]=name
    for s_row in standard.index:
        fb_name=standard['Player'][s_row]
        fb_team=standard['Squad'][s_row]
        fb_pos=standard['Pos'][s_row]
        if name==fb_name or first_name+' '+second_name==fb_name: #find names which are totally equal
            checked=True
            #print(name,' = ',fb_name,end='\n')
    if checked==False: #find names which are not totally equal
        for s_row in standard.index: 
            fb_name=standard['Player'][s_row]
            fb_team=standard['Squad'][s_row]
            fb_pos=standard['Pos'][s_row]
            if team_name==fb_team:
                if web_name in fb_name or second_name in fb_name:
                    #print(name,' = ',fb_name,end='\n')
                    standard.loc[standard['Player']==fb_name,'Player']=name
                    checked=True
                elif first_name in fb_name and pos in fb_pos:
                    standard.loc[standard['Player']==fb_name,'Player']=name
                    checked=True
                    #print(name,' = ',fb_name,end='\n')
players

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name,name
0,100.0,100.0,41270,0,0,0,0,0,DF,0.7,...,284,94,NaN,,4.0,,NaN,,Arsenal,David Luiz
1,100.0,100.0,54694,0,0,-3,3,0,MF,4.3,...,39,22,NaN,,NaN,,1.0,,Arsenal,Pierre-Emerick Aubameyang
2,NaN,NaN,59966,-1,1,-2,2,0,FW,1.7,...,61,17,NaN,,NaN,,3.0,,Arsenal,Alexandre Lacazette
3,100.0,100.0,69140,0,0,0,0,0,DF,1.0,...,395,149,NaN,,NaN,,NaN,,Arsenal,Shkodran Mustafi
4,NaN,NaN,80201,0,0,0,0,2,GK,5.7,...,160,7,NaN,,NaN,,NaN,,Arsenal,Bernd Leno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,100.0,100.0,111291,0,0,-2,2,0,DF,0.0,...,336,119,NaN,,NaN,,NaN,,Wolves,Fernando Marçal
421,NaN,NaN,437858,0,0,-2,2,0,MF,-0.3,...,375,167,NaN,,NaN,,NaN,,Wolves,Vitor Vitinha
422,NaN,NaN,441271,0,0,0,0,0,DF,-0.5,...,361,130,NaN,,NaN,,NaN,,Wolves,Ki-Jana Hoever
423,NaN,NaN,200402,0,0,1,-1,0,DF,3.0,...,147,44,NaN,,NaN,,NaN,,Wolves,Nélson Semedo
424,75.0,75.0,448514,0,0,0,0,1,DF,3.2,...,293,101,NaN,,NaN,,NaN,,Wolves,Rayan Ait Nouri

In [147]:
posts = players.groupby('element_type')
posts.groups

{'DF': Int64Index([  0,   3,   6,   7,   8,   9,  10,  17,  22,  27,
             ...
             407, 408, 410, 414, 416, 417, 420, 422, 423, 424],
            dtype='int64', length=158),
 'FW': Int64Index([  2,  14,  32,  36,  46,  54,  58,  65,  66,  70,  72,  81,  92,
              93, 103, 109, 115, 126, 136, 138, 140, 153, 155, 176, 182, 193,
             200, 211, 219, 226, 237, 250, 256, 260, 267, 279, 280, 293, 298,
             301, 302, 303, 314, 321, 326, 333, 335, 339, 344, 360, 362, 364,
             383, 390, 394, 409, 419],
            dtype='int64'),
 'GK': Int64Index([  4,  21,  48,  59,  74,  79,  88, 102, 106, 130, 146, 156, 164,
             172, 208, 216, 222, 246, 259, 285, 317, 323, 340, 370, 386, 406],
            dtype='int64'),
 'MF': Int64Index([  1,   5,  11,  12,  13,  15,  16,  18,  19,  20,
             ...
             399, 400, 404, 405, 411, 412, 413, 415, 418, 421],
            dtype='int64', length=184)}

In [148]:
GK = posts.get_group('GK')
DF = posts.get_group('DF')
MF = posts.get_group('MF')
FW = posts.get_group('FW')

In [149]:
pd.options.mode.chained_assignment = None
def add_cl(POST,DF,CL):
    POST[CL] = 0 #add new coloumn to the end
    for row in POST.index:
        team_id = POST['team'][row] #get team id from post
        team_row = DF.loc[DF['id'] == team_id] #get specific row for team id 
        POST[CL][row] = team_row[CL] #update coloumn
    return POST

In [151]:
add_cl(GK,teams_df,'strength_defence_home')
add_cl(GK,teams_df,'strength_defence_away')
add_cl(DF,teams_df,'strength_attack_home')
add_cl(DF,teams_df,'strength_attack_away')
add_cl(DF,teams_df,'strength_defence_home')
add_cl(DF,teams_df,'strength_defence_away')
add_cl(MF,teams_df,'strength_attack_home')
add_cl(MF,teams_df,'strength_attack_away')
add_cl(MF,teams_df,'strength_defence_home')
add_cl(MF,teams_df,'strength_defence_away')
add_cl(FW,teams_df,'strength_attack_home')
add_cl(FW,teams_df,'strength_attack_away')

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,team_name,name,strength_attack_home,strength_attack_away
2,NaN,NaN,59966,-1,1,-2,2,0,FW,1.7,...,NaN,,NaN,,3.0,,Arsenal,Alexandre Lacazette,1170,1210
14,NaN,NaN,205533,0,0,-4,4,0,FW,1.3,...,NaN,,NaN,,NaN,,Arsenal,Edward Nketiah,1170,1210
32,100.0,100.0,221239,0,0,-2,2,0,FW,0.0,...,NaN,,NaN,,NaN,,Aston Villa,Keinan Davis,1150,1150
36,NaN,NaN,178301,0,0,1,-1,2,FW,7.3,...,NaN,,NaN,,3.0,,Aston Villa,Ollie Watkins,1150,1150
46,NaN,NaN,115382,0,0,-1,1,1,FW,0.5,...,NaN,,NaN,,1.0,,Brighton,Neal Maupay,1150,1180
54,100.0,75.0,233425,-1,1,-2,2,0,FW,-0.8,...,NaN,,NaN,,NaN,,Brighton,Aaron Connolly,1150,1180
58,100.0,100.0,50175,0,0,0,0,1,FW,2.0,...,NaN,,NaN,,NaN,,Brighton,Danny Welbeck,1150,1180
65,100.0,100.0,44683,0,0,-2,2,0,FW,0.3,...,NaN,,NaN,,3.0,,Burnley,Jay Rodriguez,1120,1190
66,100.0,100.0,44699,0,0,0,0,0,FW,0.0,...,NaN,,NaN,,1.0,,Burnley,Ashley Barnes,1120,1190
70,NaN,NaN,60689,0,0,-3,3,0,FW,1.5,...,NaN,,NaN,,1.0,,Burnley,Chris Wood,1120,1190
72,NaN,NaN,81183,0,0,-1,1,0,FW,-1.0,...,NaN,,NaN,,NaN,,Burnley,Matej Vydra,1120,1190
81,NaN,NaN,44346,0,0,-3,3,0,FW,1.0,...,NaN,,4.0,,NaN,,Chelsea,Olivier Giroud,1240,1280
92,100.0,100.0,165153,0,0,0,0,1,FW,6.3,...,NaN,,NaN,,1.0,,Chelsea,Timo Werner,1240,1280
93,NaN,NaN,173879,0,0,-3,3,0,FW,7.3,...,NaN,,NaN,,NaN,,Chelsea,Tammy Abraham,1240,1280
103,100.0,100.0,94245,0,0,-2,2,0,FW,1.3,...,NaN,,NaN,,NaN,,Crystal Palace,Michy Batshuayi,1100,1150
109,100.0,100.0,54861,0,0,0,0,0,FW,1.0,...,NaN,,NaN,,NaN,,Crystal Palace,Christian Benteke,1100,1150
115,100.0,100.0,80146,0,0,-3,3,0,FW,3.7,...,NaN,,NaN,,4.0,,Crystal Palace,Jordan Ayew,1100,1150
126,100.0,100.0,66838,0,0,0,0,0,FW,0.2,...,NaN,,NaN,,NaN,,Everton,Cenk Tosun,1150,1170
136,NaN,NaN,177815,0,0,8,-8,2,FW,6.8,...,NaN,,NaN,,NaN,,Everton,Dominic Calvert-Lewin,1150,1170
138,100.0,100.0,212319,0,0,-2,2,0,FW,1.2,...,NaN,,NaN,,2.0,,Everton,Richarlison,1150,1170
140,0.0,0.0,242058,0,0,-2,2,0,FW,0.0,...,NaN,,NaN,,NaN,,Everton,Moise Kean,1150,1170
153,NaN,NaN,96994,0,0,-2,2,0,FW,3.3,...,NaN,,NaN,,NaN,,Fulham,Bobby Decordova-Reid,1020,1030
155,NaN,NaN,128389,0,0,-3,3,0,FW,2.3,...,NaN,,2.0,,2.0,,Fulham,Aleksandar Mitrović,1020,1030
176,100.0,100.0,101668,0,0,1,-1,3,FW,7.8,...,NaN,,NaN,,1.0,,Leicester City,Jamie Vardy,1190,1190
182,NaN,NaN,173515,0,0,-4,4,0,FW,1.0,...,NaN,,NaN,,5.0,,Leicester City,Kelechi Iheanacho,1190,1190
193,NaN,NaN,149828,0,0,0,0,0,FW,1.0,...,NaN,,NaN,,NaN,,Leicester City,Islam Slimani,1190,1190
200,NaN,NaN,106617,0,0,6,-6,1,FW,3.7,...,NaN,,NaN,,2.0,,Leeds United,Patrick Bamford,1060,1110
211,100.0,100.0,80954,0,0,-3,3,0,FW,0.3,...,NaN,,5.0,,NaN,,Leeds United,Rodrigo,1060,1110
219,NaN,NaN,92217,0,0,-3,3,0,FW,4.0,...,NaN,,NaN,,4.0,,Liverpool,Roberto Firmino,1240,1320
226,NaN,NaN,152760,0,0,-3,3,0,FW,1.3,...,NaN,,NaN,,NaN,,Liverpool,Divock Origi,1240,1320
237,100.0,75.0,37572,0,0,-2,2,0,FW,1.5,...,NaN,,NaN,,2.0,,Manchester City,Sergio Agüero,1260,1320
250,100.0,100.0,205651,0,0,-2,2,0,FW,5.2,...,NaN,,NaN,,5.0,,Manchester City,Gabriel Fernando Jesus,1260,1320
256,NaN,NaN,463034,0,0,-1,1,0,FW,1.5,...,NaN,,NaN,,NaN,,Manchester City,Liam Delap,1260,1320
260,NaN,NaN,58498,0,0,-3,3,0,FW,0.5,...,NaN,,NaN,,NaN,,Manchester Utd,Odion Ighalo,1220,1230
267,100.0,100.0,148225,0,0,-3,3,0,FW,1.8,...,NaN,,NaN,,4.0,,Manchester Utd,Anthony Martial,1220,1230
279,100.0,100.0,40720,0,0,0,0,0,FW,2.5,...,NaN,,NaN,,NaN,,Manchester Utd,Edinson Cavani,1220,1230
280,NaN,NaN,40142,-1,1,-3,3,0,FW,1.0,...,NaN,,NaN,,NaN,,Newcastle Utd,Andy Carroll,1100,1120
293,NaN,NaN,180974,0,0,-3,3,0,FW,1.0,...,NaN,,NaN,,NaN,,Newcastle Utd,Joelinton Cássio Joelinton,1100,1120
298,75.0,75.0,75115,0,0,0,0,1,FW,3.6,...,NaN,,NaN,,1.0,,Newcastle Utd,Callum Wilson,1100,1120
301,100.0,75.0,195473,0,0,0,0,0,FW,2.2,...,NaN,,NaN,,NaN,,Sheffield Utd,Rhian Brewster,1110,1130
302,NaN,NaN,18867,0,0,-3,3,0,FW,0.5,...,NaN,,NaN,,1.0,,Sheffield Utd,Billy Sharp,1110,1130
303,100.0,100.0,27436,0,0,-2,2,0,FW,3.5,...,NaN,,NaN,,NaN,,Sheffield Utd,David McGoldrick,1110,1130
314,NaN,NaN,169432,0,0,-3,3,0,FW,2.2,...,NaN,,NaN,,NaN,,Sheffield Utd,Oliver McBurnie,1110,1130
321,NaN,NaN,20452,0,0,-3,3,0,FW,0.3,...,NaN,,NaN,,NaN,,Southampton,Shane Long,1140,1200
326,0.0,0.0,84939,0,0,-2,2,1,FW,0.0,...,NaN,,NaN,,1.0,,Southampton,Danny Ings,1140,1200
333,NaN,NaN,200439,0,0,-1,1,1,FW,5.7,...,NaN,,NaN,,NaN,,Southampton,Che Adams,1140,1200
335,NaN,NaN,220598,0,0,-3,3,0,FW,-0.5,...,NaN,,NaN,,NaN,,Southampton,Michael Obafemi,1140,1200
339,NaN,NaN,200088,0,0,0,0,0,FW,-0.3,...,NaN,,NaN,,NaN,,Southampton,Daniel N'Lundulu,1140,1200
344,NaN,NaN,78830,0,0,5,-5,3,FW,6.0,...,NaN,,4.0,,1.0,,Tottenham,Harry Kane,1190,1240
360,NaN,NaN,245824,0,0,0,0,0,FW,0.2,...,NaN,,NaN,,NaN,,Tottenham,Carlos Vinicius,1190,1240
362,100.0,100.0,171975,0,0,0,0,1,FW,1.5,...,NaN,,NaN,,NaN,,West Brom,Callum Robinson,1020,1020
364,100.0,0.0,49440,0,0,-3,3,0,FW,-0.3,...,NaN,,NaN,,2.0,,West Brom,Hal Robson-Kanu,1020,1020
383,NaN,NaN,180294,0,0,-1,1,0,FW,3.3,...,NaN,,NaN,,NaN,,West Brom,Karlan Grant,1020,1020
390,50.0,50.0,57531,0,0,-3,3,0,FW,0.0,...,NaN,,NaN,,2.0,,West Ham,Michail Antonio,1150,1160
394,100.0,100.0,103123,0,0,-4,4,0,FW,4.3,...,NaN,,NaN,,NaN,,West Ham,Sébastien Haller,1150,1160
409,NaN,NaN,102057,0,0,-1,1,0,FW,4.0,...,NaN,,NaN,,1.0,,Wolves,Raúl Jiménez,1180,1220
419,NaN,NaN,449988,0,0,-3,3,0,FW,0.0,...,NaN,,NaN,,NaN,,Wolves,Fabio Silva,1180,1220

In [154]:
GK=GK[['id','web_name','first_name','second_name','team'
       ,'now_cost','cost_change_start'
       ,'total_points','selected_by_percent','clean_sheets','goals_conceded','saves','minutes'
       ,'chance_of_playing_next_round','event_points'
       ,'value_season','value_form'
       ,'penalties_saved','bonus','bps'
       ,'cost_change_event','transfers_in_event', 'transfers_out_event'
       ,'form','points_per_game'
       ,'dreamteam_count','in_dreamteam'
       
       
       ,'strength_defence_home','strength_defence_away','ict_index','influence'       
       ,'ict_index_rank_type', 'influence_rank_type','ict_index_rank','influence_rank'       
       ,'yellow_cards', 'red_cards'       
       ,'transfers_in','transfers_out'
       , 'ep_next'
       ,'status'            
       ,'own_goals'
       ,'team_code'                
       ,'name']]
GK.index=list(range(len(GK.index)))

In [155]:
FW=FW[['id','web_name','first_name','second_name','team'
       ,'now_cost','cost_change_start'
       ,'total_points','selected_by_percent','minutes','goals_scored','assists'
       ,'penalties_order','penalties_missed'
       
       ,'chance_of_playing_next_round','event_points'
       ,'value_season','value_form'
       ,'bonus','bps'
       
       ,'yellow_cards', 'red_cards'
       
       ,'corners_and_indirect_freekicks_order'
       , 'direct_freekicks_order'
       
       ,'cost_change_event','transfers_in_event', 'transfers_out_event'
       ,'form','points_per_game'
       ,'dreamteam_count','in_dreamteam'
       
       
       ,'strength_attack_home','strength_attack_away'
       ,'ict_index','influence','creativity','threat'
       ,'ict_index_rank_type', 'ict_index_rank'
       ,'influence_rank','influence_rank_type'
       ,'creativity_rank','creativity_rank_type'
       ,'threat_rank', 'threat_rank_type' 
       
            
       ,'transfers_in','transfers_out'
       , 'ep_next'
       ,'status'            
       ,'own_goals'
       ,'team_code'
       ,'name']]
FW.index=list(range(len(FW.index)))

In [156]:
DF=DF[['id','web_name','first_name','second_name','team'
       ,'now_cost','cost_change_start'
       ,'total_points','selected_by_percent','minutes','clean_sheets','goals_scored','assists','goals_conceded'
       
       ,'penalties_order','penalties_missed'
       ,'corners_and_indirect_freekicks_order'
       , 'direct_freekicks_order'
       
       ,'chance_of_playing_next_round','event_points'
       ,'value_season','value_form'
       ,'bonus','bps'       
       
       ,'yellow_cards', 'red_cards'
       
       ,'cost_change_event','transfers_in_event', 'transfers_out_event'
       ,'form','points_per_game'
       ,'dreamteam_count','in_dreamteam'
              
       ,'strength_attack_home','strength_attack_away'
       ,'strength_defence_home','strength_defence_away'       
       
       ,'ict_index','influence','creativity','threat'
       ,'ict_index_rank_type', 'ict_index_rank'
       ,'influence_rank','influence_rank_type'
       ,'creativity_rank','creativity_rank_type'
       ,'threat_rank', 'threat_rank_type' 
       
              
       ,'transfers_in','transfers_out'
       , 'ep_next'
       ,'status'            
       ,'own_goals'
       ,'team_code'
       ,'name']]
DF.index=list(range(len(DF.index)))

In [157]:
MF=MF[['id','web_name','first_name','second_name','team'
       ,'now_cost','cost_change_start'
       ,'total_points','selected_by_percent','minutes','goals_scored','assists','clean_sheets','goals_conceded'
       
       ,'penalties_order','penalties_missed'
       ,'corners_and_indirect_freekicks_order'
       , 'direct_freekicks_order'
       
       ,'chance_of_playing_next_round','event_points'
       ,'value_season','value_form'
       ,'bonus','bps'       
       
       ,'yellow_cards', 'red_cards'
       
       ,'cost_change_event','transfers_in_event', 'transfers_out_event'
       ,'form','points_per_game'
       ,'dreamteam_count','in_dreamteam'
              
       ,'strength_attack_home','strength_attack_away'
       ,'strength_defence_home','strength_defence_away'       
       
       ,'ict_index','influence','creativity','threat'
       ,'ict_index_rank_type', 'ict_index_rank'
       ,'influence_rank','influence_rank_type'
       ,'creativity_rank','creativity_rank_type'
       ,'threat_rank', 'threat_rank_type' 
       
              
       ,'transfers_in','transfers_out'
       , 'ep_next'
       ,'status'            
       ,'own_goals'
       ,'team_code'
       ,'name']]
MF.index=list(range(len(MF.index)))
MF

,id,web_name,first_name,second_name,team,now_cost,cost_change_start,total_points,selected_by_percent,minutes,...,creativity_rank_type,threat_rank,threat_rank_type,transfers_in,transfers_out,ep_next,status,own_goals,team_code,name
0,4,Aubameyang,Pierre-Emerick,Aubameyang,1,117,-3,33,12.3,806,...,24,36,20,454467,2729565,4.3,a,0,3,Pierre-Emerick Aubameyang
1,9,Xhaka,Granit,Xhaka,1,53,-2,13,0.5,497,...,129,212,111,21657,53149,1.5,a,0,3,Granit Xhaka
2,18,Pépé,Nicolas,Pépé,1,76,-4,11,0.8,277,...,122,102,53,22051,126798,0.0,s,0,3,Nicolas Pépé
3,20,Willock,Joseph,Willock,1,48,-2,1,0.1,56,...,171,342,163,2684,6999,0.7,a,0,3,Joseph Willock
4,21,Nelson,Reiss,Nelson,1,52,-3,1,0.0,45,...,168,571,227,1069,5033,0.7,a,0,3,Reiss Nelson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,465,Traoré,Adama,Traoré,20,62,-3,13,6.9,430,...,78,177,95,248447,1122401,0.5,a,0,39,Adama Traoré
180,466,Neves,Rúben Diogo,da Silva Neves,20,53,-2,16,1.4,623,...,44,66,33,36193,121887,1.5,a,0,39,Rúben Diogo Neves
181,469,Podence,Daniel,Castelo Podence,20,55,0,31,3.4,584,...,41,69,36,639628,440879,3.0,a,0,39,Daniel Podence
182,474,Neto,Pedro,Lomba Neto,20,55,0,38,1.9,666,...,10,45,24,202152,105451,3.7,a,0,39,Pedro Neto
183,515,Vitinha,Vitor,Ferreira,20,48,-2,3,0.0,26,...,157,535,214,978,2876,-0.3,a,0,39,Vitor Vitinha

In [163]:
FW['xG']=0.0
FW['xA']=0.0
for row in FW.index:
    name=FW['name'][row]
    FW['xG'][row]=standard.loc[standard['Player']==name,'xG']
    FW['xA'][row]=standard.loc[standard['Player']==name,'xA']
FW[['name','xG','xA']]

                          name   xG   xA
0          Alexandre Lacazette  2.2  0.4
1               Edward Nketiah  1.0  0.2
2                 Keinan Davis  0.0  0.0
3                Ollie Watkins  4.9  0.5
4                  Neal Maupay  4.8  0.6
5               Aaron Connolly  0.5  0.1
6                Danny Welbeck  1.0  0.5
7                Jay Rodriguez  0.3  0.1
8                Ashley Barnes  0.8  0.2
9                   Chris Wood  1.9  0.2
10                 Matej Vydra  0.3  0.4
11              Olivier Giroud  0.0  0.0
12                 Timo Werner  3.7  1.3
13               Tammy Abraham  3.0  0.9
14             Michy Batshuayi  0.3  0.8
15           Christian Benteke  0.0  0.1
16                 Jordan Ayew  0.8  0.0
17                  Cenk Tosun  0.0  0.1
18       Dominic Calvert-Lewin  6.0  0.5
19                 Richarlison  3.2  1.1
20                  Moise Kean  0.0  0.0
21        Bobby Decordova-Reid  2.1  0.1
22         Aleksandar Mitrović  4.1  1.0
23                 Jamie Vardy  7.9  1.2
24           Kelechi Iheanacho  0.1  0.5
25               Islam Slimani  0.0  0.0
26             Patrick Bamford  6.1  0.4
27                     Rodrigo  2.1  0.6
28             Roberto Firmino  4.2  1.3
29                Divock Origi  0.0  0.0
30               Sergio Agüero  0.2  0.6
31      Gabriel Fernando Jesus  1.2  0.4
32                  Liam Delap  0.0  0.0
33                Odion Ighalo  0.0  0.0
34             Anthony Martial  1.1  0.0
35              Edinson Cavani  0.8  0.3
36                Andy Carroll  0.5  0.0
37  Joelinton Cássio Joelinton  0.2  0.4
38               Callum Wilson  5.6  0.8
39              Rhian Brewster  0.3  0.4
40                 Billy Sharp  1.1  0.0
41            David McGoldrick  0.8  0.5
42             Oliver McBurnie  1.4  0.4
43                  Shane Long  0.0  0.0
44                  Danny Ings  2.7  0.7
45                   Che Adams  2.4  1.5
46             Michael Obafemi  0.0  0.0
47            Daniel N'Lundulu  0.0  0.0
48                  Harry Kane  5.9  3.8
49             Carlos Vinicius  0.1  0.0
50             Callum Robinson  0.5  0.4
51             Hal Robson-Kanu  0.1  0.0
52                Karlan Grant  1.1  0.0
53             Michail Antonio  2.8  0.4
54            Sébastien Haller  1.5  0.8
55                Raúl Jiménez  2.2  0.7
56                 Fabio Silva  0.1  0.0